name: CI

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
